name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  binary:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.6
    with:
      working_directory: './examples/binary/'
  complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.6
    with:
      working_directory: './examples/complete/'
  key-vault:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.6
    with:
      working_directory: './examples/key-value/'
